# Generated by Django 5.1.6 on 2026-09-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_notification_link_notification_notification_type_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAccessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='All-Access VIP Master Pass', max_length=150)),
                ('tagline', models.CharField(default='Unlock Every Single Course with One Single Amount', max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, default=4999.0, max_digits=8)),
                ('offer_price', models.DecimalField(decimal_places=2, default=999.0, max_digits=8)),
                ('features', models.TextField(default='Full lifetime access to all current and upcoming courses\nInstant certificate eligibility on completion\nAccess to all downloadable project source codes\nDirect instructor support in Q&A\nResume & placement drive access', help_text='Line-separated list of benefits shown to students')),
                ('is_active', models.BooleanField(default=True)),
                ('upi_id', models.CharField(default='7218858764@ybl', max_length=100)),
                ('upi_number', models.CharField(default='7218858764', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='is_all_access',
            field=models.BooleanField(default=False, help_text='Designates whether this payment is for the All-Courses Pass'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
