# Generated by Django 5.1.6 on 2026-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_allaccessplan_payment_is_all_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allaccessplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=365, help_text='Pass access duration in days (default 365 days / 1 year)'),
        ),
        migrations.AlterField(
            model_name='allaccessplan',
            name='features',
            field=models.TextField(default='Full 1 Year Access to all current and upcoming courses (365 Days)\nInstant certificate eligibility on completion\nAccess to all downloadable project source codes\nDirect instructor support in Q&A\nResume & placement drive access', help_text='Line-separated list of benefits shown to students'),
        ),
        migrations.AlterField(
            model_name='allaccessplan',
            name='tagline',
            field=models.CharField(default='Unlock Every Single Course with One Single Amount (1 Year Access)', max_length=255),
        ),
    ]
