# Generated by Django 5.1.6 on 2026-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_allaccessplan_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allaccessplan',
            name='upi_id',
            field=models.CharField(default='sunnywaghmode8@axl', max_length=100),
        ),
    ]
