services:
  - type: web
    name: sj-tech-classes-lms
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate && python create_admin_superuser.py && python seed_courses_and_videos.py && gunicorn lms_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: lms_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
