from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_router, name='dashboard'),
    path('student/', views.student_dashboard, name='student_dashboard'),
    path('instructor/', views.instructor_dashboard, name='instructor_dashboard'),
    path('instructor/course/create/', views.create_course, name='create_course'),
    path('instructor/course/<int:course_id>/edit/', views.edit_course, name='edit_course'),
    path('instructor/course/<int:course_id>/delete/', views.delete_course, name='delete_course'),
    path('instructor/course/<int:course_id>/manage/', views.manage_course_content, name='manage_course_content'),
    path('instructor/lesson/<int:lesson_id>/edit/', views.edit_lesson, name='edit_lesson'),
    path('instructor/lesson/<int:lesson_id>/delete/', views.delete_lesson, name='delete_lesson'),
    path('instructor/module/<int:module_id>/delete/', views.delete_module, name='delete_module'),
    path('instructor/project-file/<int:project_id>/delete/', views.delete_project_file, name='delete_project_file'),
    path('instructor/builder/', views.course_builder, name='course_builder'),
    path('instructor/live/schedule/', views.schedule_live_class, name='schedule_live_class'),
    path('instructor/live/<int:live_class_id>/edit/', views.edit_live_class, name='edit_live_class'),
    path('instructor/live/<int:live_class_id>/delete/', views.delete_live_class, name='delete_live_class'),
    path('instructor/project-zip/upload/', views.upload_project_zip, name='upload_project_zip'),
    path('placements/manage/', views.manage_placements, name='manage_placements'),
    path('placements/application/<int:application_id>/status/', views.update_application_status, name='update_application_status'),
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/payment/<int:payment_id>/approve/', views.approve_payment, name='approve_payment'),
    path('admin-panel/payment/<int:payment_id>/reject/', views.reject_payment, name='reject_payment'),
    path('admin-panel/certificate/generate/<int:enrollment_id>/', views.admin_generate_certificate, name='admin_generate_certificate'),
    path('admin-panel/certificate/<int:certificate_id>/edit/', views.admin_edit_certificate, name='admin_edit_certificate'),
    path('admin-panel/certificate/<int:certificate_id>/regenerate/', views.admin_regenerate_certificate, name='admin_regenerate_certificate'),
    path('admin-panel/create-coupon/', views.create_coupon, name='create_coupon'),
    path('admin-panel/student/add/', views.admin_add_student, name='admin_add_student'),
    path('admin-panel/student/<int:student_id>/edit/', views.admin_edit_student, name='admin_edit_student'),
    path('admin-panel/student/<int:student_id>/delete/', views.admin_delete_student, name='admin_delete_student'),
    path('admin-panel/add-instructor/', views.add_instructor, name='add_instructor'),
    path('admin-panel/instructor/<int:instructor_id>/edit/', views.edit_instructor, name='edit_instructor'),
    path('admin-panel/instructor/<int:instructor_id>/delete/', views.delete_instructor, name='delete_instructor'),
    path('admin-panel/instructor/<int:instructor_id>/approve/', views.approve_instructor, name='approve_instructor'),
    path('admin-panel/instructor/<int:instructor_id>/reject/', views.reject_instructor, name='reject_instructor'),
    path('admin-panel/enroll-free/', views.admin_enroll_student_free, name='admin_enroll_student_free'),
    path('admin-panel/unlock-all-courses-free/', views.admin_unlock_all_courses_free, name='admin_unlock_all_courses_free'),
    path('admin-panel/broadcast-offer/', views.admin_broadcast_offer, name='broadcast_offer'),
    path('admin-panel/toggle-all-access/', views.toggle_all_access_offer, name='toggle_all_access_offer'),
    path('admin-panel/update-all-access-plan/', views.admin_update_all_access_plan, name='admin_update_all_access_plan'),
    path('admin-panel/feedback/add/', views.admin_add_feedback, name='admin_add_feedback'),
    path('admin-panel/feedback/<int:feedback_id>/update/', views.admin_update_feedback, name='admin_update_feedback'),
    path('admin-panel/feedback/<int:feedback_id>/delete/', views.admin_delete_feedback, name='admin_delete_feedback'),
    path('admin-panel/feedback/<int:feedback_id>/toggle/', views.admin_toggle_feedback_approval, name='admin_toggle_feedback_approval'),
    path('instructor/assignments/', views.instructor_assignments, name='instructor_assignments'),
    path('instructor/assignments/<int:submission_id>/grade/', views.grade_assignment, name='grade_assignment'),
]

