# Generated by Django 5.1.6 on 2026-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_all_access',
            field=models.BooleanField(default=False, help_text='Designates whether the student has unlocked all courses via All-Access Pass'),
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in_session_key',
            field=models.CharField(blank=True, help_text='Active session key for single device login enforcement', max_length=40, null=True),
        ),
    ]
