# Generated by Django 5.1.6 on 2026-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_has_all_access_user_logged_in_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_access_valid_until',
            field=models.DateTimeField(blank=True, help_text='Expiration date & time for 1-year All-Access Pass', null=True),
        ),
    ]
