# Generated by Django 5.1.6 on 2026-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_all_access_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this instructor has been approved by an administrator.'),
        ),
    ]
