# Generated by Django 5.1.6 on 2026-08-02 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_liveclass_projectfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('location', models.CharField(default='Pune / Solapur / Remote', max_length=255)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-Time', max_length=20)),
                ('salary_package', models.CharField(help_text='e.g. 4.5 LPA - 8.0 LPA', max_length=100)),
                ('skills_required', models.CharField(help_text='e.g. Python, Django, HTML, CSS, SQL', max_length=500)),
                ('experience_required', models.CharField(default='Freshers / 0-2 Years', max_length=100)),
                ('description', models.TextField()),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('designation', models.CharField(max_length=255)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='placed_students/')),
                ('placed_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('github_portfolio', models.URLField(blank=True, null=True)),
                ('cover_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.jobplacement')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'student')},
            },
        ),
    ]
