# Generated by Django 5.1.6 on 2026-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_jobplacement_placementrecord_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='run_instructions',
            field=models.TextField(blank=True, default='1. Extract the downloaded .ZIP file.\n2. Open terminal inside the project directory.\n3. Create virtual environment: python -m venv venv\n4. Activate venv: venv\\Scripts\\activate (Windows) or source venv/bin/activate (Linux/Mac)\n5. Install dependencies: pip install -r requirements.txt\n6. Run migrations: python manage.py migrate\n7. Start server: python manage.py runserver'),
        ),
    ]
