# Generated by Django 5.1.6 on 2026-08-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_projectfile_run_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobplacement',
            name='official_apply_url',
            field=models.URLField(default='https://careers.tcs.com', help_text='Official company job portal link uploaded by Admin'),
        ),
    ]
