# Generated by Django 5.1.6 on 2026-08-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_jobplacement_official_apply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='description',
            field=models.TextField(blank=True, default='Complete production-ready web application source code with database models and setup guide.'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_free_download',
            field=models.BooleanField(default=True, help_text='Allow free download for all registered students in Projects Portal'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='tech_stack',
            field=models.CharField(default='Python 3 / Django / SQLite / HTML5', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to='courses.course'),
        ),
    ]
