# Generated by Django 5.1.6 on 2026-08-02 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_projectfile_description_projectfile_is_free_download_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set price for paid project downloads (e.g. ₹299)', max_digits=8),
        ),
        migrations.CreateModel(
            name='ProjectPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_purchases', to='payments.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.projectfile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'project')},
            },
        ),
    ]
