# Generated by Django 5.1.6 on 2026-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_discussion_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='online_thumbnail_url',
            field=models.URLField(blank=True, help_text='External online image URL for course thumbnail', max_length=500, null=True),
        ),
    ]
