# Generated by Django 5.1.6 on 2026-08-03 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_online_thumbnail_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementrecord',
            name='student_image',
        ),
        migrations.AlterField(
            model_name='placementrecord',
            name='package_lpa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='placementrecord',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='e.g. TCS, Infosys, Wipro, Amazon, Google, Accenture', max_length=150)),
                ('topic', models.CharField(help_text='e.g. Python, Django, React, SQL, Data Structures, AWS', max_length=150)),
                ('question_text', models.TextField(help_text='The interview question')),
                ('answer_text', models.TextField(help_text='Detailed sample answer, explanation, or code snippet')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('category', models.CharField(choices=[('Technical', 'Technical Round'), ('Coding', 'Coding / Hands-on'), ('System Design', 'System Architecture & Design'), ('HR / Behavioral', 'HR & Behavioral Round')], default='Technical', max_length=30)),
                ('code_snippet', models.TextField(blank=True, help_text='Optional Python/Java/JS code example for this answer', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on Top Company Questions list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
