# Generated by Django 5.1.6 on 2026-08-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_placementrecord_student_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_role_company', models.CharField(help_text='e.g. Placed @ TCS (7.0 LPA)', max_length=150)),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5 stars')),
                ('feedback_text', models.TextField()),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_feedback/')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
