# Generated by Django 5.1.6 on 2026-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
