# Generated by Django 5.1.6 on 2026-09-06 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_assignmentsubmission_feedback_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional action link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('offer', 'Prize Offer / Discount'), ('course', 'Course Update')], default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='BroadcastOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('offer_badge', models.CharField(default='Special Offer', help_text='e.g. 🎁 50% OFF, Mega Sale, Prize Offer', max_length=50)),
                ('action_url', models.CharField(blank=True, help_text='Button URL e.g. /payments/all-access/', max_length=255, null=True)),
                ('action_button_text', models.CharField(default='Claim Offer Now', max_length=50)),
                ('target_audience', models.CharField(choices=[('all_students', 'All Students'), ('all_users', 'All Users'), ('unenrolled', 'Students without Any Course')], default='all_students', max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
