# Generated by Django 5.1.6 on 2026-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_notification_link_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_title',
            field=models.CharField(blank=True, help_text='Custom course title displayed on certificate.', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='duration_hours',
            field=models.IntegerField(blank=True, help_text='Custom duration in hours displayed on certificate.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='Custom instructor/signer name.', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instructor_title',
            field=models.CharField(blank=True, help_text='Custom instructor/signer title.', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Custom issue date displayed on certificate.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student_name',
            field=models.CharField(blank=True, help_text='Custom student full name displayed on certificate.', max_length=200),
        ),
    ]
