# Generated by Django 5.1.6 on 2026-09-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_certificate_course_title_certificate_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading of the slide (e.g. Learn Today,)', max_length=255)),
                ('highlight_text', models.CharField(blank=True, help_text='Highlighted text in yellow (e.g. Build Tomorrow)', max_length=255, null=True)),
                ('badge_text', models.CharField(default='SJ TECH CLASSES', help_text='Pill badge text', max_length=100)),
                ('badge_icon', models.CharField(default='fa-rocket', help_text='FontAwesome icon (e.g. fa-rocket, fa-qrcode, fa-briefcase, fa-code)', max_length=50)),
                ('description', models.TextField(help_text='Subtitle or description text')),
                ('image', models.ImageField(blank=True, help_text='Upload custom hero banner image (Cloudinary or local)', null=True, upload_to='carousel_slides/')),
                ('online_image_url', models.URLField(blank=True, help_text='Optional external image URL if not uploading file directly', max_length=500, null=True)),
                ('primary_btn_text', models.CharField(default='Explore All Courses', max_length=100)),
                ('primary_btn_url', models.CharField(default='/courses/', max_length=255)),
                ('secondary_btn_text', models.CharField(blank=True, default='Placement Drive', max_length=100, null=True)),
                ('secondary_btn_url', models.CharField(blank=True, default='/placements/', max_length=255, null=True)),
                ('gradient_css', models.CharField(default='linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)', help_text='Background gradient CSS (e.g. linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%))', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lowest number appears first)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this slide on the home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
